spring.jpa.show-sql: true

security:
  oauth2:
    client:
      clientId: 6bfa61f1d7bc9e1e4d8efe14c08f64dd16802304f2da62673242b10737a8b263
      clientSecret: fc873ef27d04f5016b2ddf46ef10fb8157c0042bd3f9e46fe0b0d086e2a34a9e
      accessTokenUri: https://gitlab.lrz.de/oauth/token
      userAuthorizationUri: https://gitlab.lrz.de/oauth/authorize
      scope:
        - read_user
        - api
    resource:
      userInfoUri: https://gitlab.lrz.de/api/v4/user


spring:
#  profiles:
#    acitve: "dev"
  application:
    name: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
server:
  port: ${PORT:8000}
zuul.host.socket-timeout-millis: 20000
zuul.host.connect-timeout-millis: 20000
ribbon.ConnectTimeout: 10000
ribbon.ReadTimeout: 10000
zuul:
  # disabling automatic adding of services into Zuul by setting ignored-services to *
  # https://cloud.spring.io/spring-cloud-netflix/multi/multi_router_and_filter_zuul.html#netflix-zuul-reverse-proxy
  ignored-services: "*"
  routes:
    project-service:
      path: "/project/**"
      service-id: project-service
      strip-prefix: false
      sensitiveHeaders: Cookie, Set-Cookie #Authentication - sensitive headers for accessing gitlab api are handed over
    ui-service:
      path: "/ui/**"
      service-id: ui-service
      strip-prefix: false
    compiler-service:
      path: "/compiler/**"
      service-id: compiler-service
      strip-prefix: false
    darkmode-service:
      path: "/darkmode/**"
      service-id: darkmode-service
      strip-prefix: false

proxy:
  auth:
    routes:
      project-service: oauth2


